config/routes.rb
Spoutlets::Application.routes.draw do
  resources :entries


  root :to => 'entries#index'
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/entry.rb
class Entry
  include Mongoid::Document
  field :title,            type: String
  field :content,          type: String
  field :happiness_level,  type: String
  field :anxiety_level,    type: String
  field :irritation_level, type: String
  field :category,         type: String
  field :published,        type: Boolean
  belongs_to :user
end

app/models/role.rb
class Role
  include Mongoid::Document
  
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String
  index({ :name => 1 }, { :unique => true })


  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/user.rb
class User
  include Mongoid::Document
  rolify
  field :provider, type: String
  field :uid, type: String
  field :name, type: String
  field :email, type: String
  has_many :entries
  attr_accessible :role_ids, :as => :admin
  attr_accessible :provider, :uid, :name, :email
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new
    @entry.published = true

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(params[:entry])
    @entry.user = current_user

    respond_to do |format|
      if @entry.save
        format.html { redirect_to user_url(current_user), notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    @entry = Entry.find(params[:id])
    @entry.user = current_user

    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    user.add_role :admin if User.count == 1 # make the first user an admin
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
    @entries = @user.entries.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/_form.html.erb
<%= simple_form_for(@entry) do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="span7">
    <%= f.input :title, wrapper: :prepend, label: false do %>
      <%= content_tag :span, "Title", class: "add-on" %>
      <%= f.input_field :title, class: "span6" %>
    <% end %>
  </div>
  <div class="span4 offset1">
    <%= f.input :published,
        as: :boolean,
        label: "Share on SpoutWall" %>
  </div>
</div>
<div class="row">
  <div class="span7">
    <%= f.input :content,
        as: :text,
        label: false,
        placeholder: "Give more details about what you're dealing with",
        input_html: { rows: 7, class: "span7" } %>
  </div>
</div>

<div class="row">
  <div class="span7">
    <div class="well">
      <div class="row">
        <div class="span2">
          <%= f.input :happiness_level,
              collection: [
                ["1 (not very)", "1"],
                ["2", "2"],
                ["3", "3"],
                ["4", "4"],
                ["5 (very)", "5"]
              ],
              include_blank: "N/A",
              label: "Happiness Level",
              input_html: { class: "span1" } %>
        </div>

        <div id="happiness-bar" class="progress progress-striped">
          <div class="bar"></div>
        </div>

        <div class="span2">
          <%= f.input :anxiety_level,
              collection: [
                ["1 (not very)", "1"],
                ["2", "2"],
                ["3", "3"],
                ["4", "4"],
                ["5 (very)", "5"]
              ],
              include_blank: "N/A",
              label: "Anxiety Level",
              input_html: { class: "span1" } %>
        </div>
        <div class="span2">
          <%= f.input :irritation_level,
              collection: [
                ["1 (not very)", "1"],
                ["2", "2"],
                ["3", "3"],
                ["4", "4"],
                ["5 (very)", "5"]
              ],
              include_blank: "N/A",
              label: "Irritation Level",
              input_html: { class: "span1" } %>
        </div>
      </div>
      <div class="row">
        <div class="span7">
          <%= f.input :category,
              collection: [
                ["other"],
                ["alcohol"],
                ["anxiety"],
                ["body image"],
                ["depression"],
                ["disability"],
                ["family"],
                ["relationships"],
              ],
              include_blank: "N/A",
              label: "Categorize your entry to understand what bothers or delights you regularly" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit, "Log it!",
      class: "btn-large btn-block  btn-primary" %>
</div>

<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h3>My Peer Community</h3>
<p>Connect with others dealing with the same issues</p>
<div class="row">
  <div class="span9">
    <!-- Entry -->
    <% @entries.each do |entry| %>
    <div class="well">
      <div class="row">
        <div class="span1">
          <span class="badge badge-info">14</span> <br />
          <span class="text-info"> been there</span>
        </div>
        <div class="span5">
          <br />
          <p><small><%= entry.content %></small></p>
          <ul class="nav nav-list">
            <li class="divider"></li>
          </ul>
        </div>
        <div class="span1">
          <br />
          <span class="muted"><small>12 hours ago</small></span>
        </div>
        <div class="span1">
          <span class="label pull-right">Anxiety</span>
        </div>
      </div>

      <div class="row">
        <div class="span4">
          <p class="muted"><small>shared
              by <i class="icon-user"></i>
                anonymous</small></p>
        </div>
        <div class="span4">
          <button class="btn btn-mini pull-right"
                  type="button"><i class="icon-ok"></i> been there</button>
        </div>
      </div>
    </div>
    <% end %><!-- end of Entry -->
  </div>
  <!-- Common Issues -->
  <div class="span2">
    <h4>Common Issues</h4>
    <span class="label">Anxiety</span>
    <span class="label">romantic issues</span>
    <span class="label">room mate</span>
    <span class="label">sexuality</span>
    <span class="label">future worries</span>
    <span class="label">diet</span>
    <span class="label">feeling lonely</span>
  </div> <!-- end of Common Issues -->
</div>

app/views/entries/new.html.erb
<h4><%= Date.today.strftime('%a %b %d, %Y') %></h4>
<hr />
<%= render 'form' %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>
<p>
  <b>Content:</b>
  <%= @entry.content %>
</p>
<p>
  <b>Happiness level:</b>
  <%= @entry.happiness_level %>
</p>
<p>
  <b>Anxiety level:</b>
  <%= @entry.anxiety_level %>
</p>
<p>
  <b>Irritation level:</b>
  <%= @entry.irritation_level %>
</p>
<p>
  <b>Category:</b>
  <%= @entry.category %>
</p>
<p>
  <b>Public:</b>
  <%= @entry.published %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/home/index.html.erb
<h3>My Peer Community</h3>
<p>connect with others dealing with the same issues</p>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">
  <div class="span2">
    <%= link_to "Spoutlets", root_path, :class => 'brand' %>
  </div>
  <!-- Right Nav -->
  <div class="span8">
    <ul class="nav pull-right">
    <% if user_signed_in? %>
      <li><a href="#"><i class="icon-white
                                icon-bookmark"></i> your therapist</a></li>
      <li class="divider-vertical"></li>
      <li><a href="#"><i class="icon-white
                                icon-bookmark"></i> your peers</a></li>
      <li class="divider-vertical"></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle"
           data-toggle="dropdown"><i class="icon-user
                                            icon-white"></i>
          your profile <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "backstory", current_user %></li>
          <li><a href="#">settings</a></li>
          <li class="divider"></li>
          <li><%= link_to 'logout', signout_path %></li>
        </ul>
      </li>
    <% else %>
      <li>
      <%= link_to 'login/register', signin_path %>
      </li>
    <% end %>
      <li class="divider-vertical"></li>
    </ul>
  </div> <!-- end of Right Nav -->
  <div class="span2">
    <%= link_to "log an entry", new_entry_path, :class => "btn btn-primary pull-right", :method => :get  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Spoutlets" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Spoutlets" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Sign in" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>Your Backstory</h3>
<div class="row">
  <div class="span12">
    <div class="hero-unit">
      <h4>What's been on your mind over time</h4>
      <p>Graph placeholder</p>
    </div>
  </div>

  <div class="span9">
    <!-- Entry -->
    <% @entries.each do |entry| %>
    <div class="well">
      <div class="row">
        <div class="span1">
          <span class="label"><%= entry.category %> </span>
        </div>
        <div class="span5">
          <br />
          <p><small><%= entry.content %></small></p>
          <ul class="nav nav-list">
            <li class="divider"></li>
          </ul>
        </div>
        <div class="span1">
          <br />
          <span class="muted"><small><%= Date.today.strftime('%a %b %d, %Y') %></small></span>
        </div>
        <div class="span1">
          <span class="badge badge-info">14</span> <br />
          <span class="text-info"> been there</span>
        </div>
      </div>

      <div class="row">
        <div class="span1 offset1">
          <p class="muted"><small>happiness</small></p>
          <div class="progress">
            <div class="bar" style="width: 20%;"></div>
          </div>
        </div>
        <div class="span1">
          <p class="muted"><small>anxiety</small></p>
          <div class="progress">
            <div class="bar" style="width: 80%;"></div>
          </div>
        </div>
        <div class="span1">
          <p class="muted"><small>irritation</small></p>
          <div class="progress">
            <div class="bar" style="width: 40%;"></div>
          </div>
        </div>
        <div class="span4">
          <button class="btn btn-mini pull-right"
                  type="button"><i class="icon-ok"></i> Share with therapist</button>
        </div>
      </div>
    </div>
    <% end %><!-- end of Entry -->
  </div>
</div>